version:  '2'

services: 
  web:
    
    build: 
      context: ./web
    environment: 
      - ImageApiUri=http://imageapi/api/image
    ports: 
      - "5000:80"
    depends_on: 
      - imageapi
  imageapi:
    build: 
      context: ./webapi
    ports: 
      - "8080:80"